# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(max_length=10)),
                ('protein_id', models.CharField(max_length=20)),
                ('mutate_position', models.IntegerField()),
                ('mut_from', models.CharField(max_length=1)),
                ('mut_to', models.CharField(max_length=1)),
                ('patient', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mutation_table',
            },
        ),
    ]
