# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_cancer_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mutation',
            table='mutations_table',
        ),
    ]
