# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_cancer_pro', '0002_auto_20180809_1205'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mutation',
            table='mutation_table',
        ),
    ]
