# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_cancer_pro', '0004_motif_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=20)),
                ('protein_length', models.IntegerField()),
            ],
            options={
                'db_table': 'protein_sequence',
            },
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
    ]
