# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_cancer_pro', '0005_auto_20180809_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refseq', models.CharField(max_length=30)),
                ('uniprot_id', models.CharField(max_length=30)),
                ('protein_name', models.TextField()),
            ],
            options={
                'db_table': 'refseq_to_uniprot',
            },
        ),
    ]
