# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 05:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('upload_time', models.DateTimeField(default=datetime.datetime(2018, 8, 14, 5, 13, 49, 140535, tzinfo=utc))),
                ('user_dir', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'user_record',
            },
        ),
    ]
