# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 02:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='upload_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 17, 2, 50, 0, 698, tzinfo=utc)),
        ),
    ]
